development:
  adapter: postgresql
  encoding: unicode
  database: rabbitmq_development
  pool: 5
  min_messages: notice

test:
  adapter: postgresql
  encoding: unicode
  database: rabbitmq_test
  pool: 5
  min_messages: notice

production:
  adapter: postgresql
  encoding: unicode
  database: rabbitmq_development
  pool: 5
  min_messages: notice
